//Listar todos
GET http://localhost:3000/api/pedidos

###

//Criar pedido
POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 2
        },
        {
            "produto_id": 2,
            "quantidade": 1
        },
        {
            "produto_id": 3,
            "quantidade": 4
        }
    ]
} 

###
// Deletar
DELETE http://localhost:3000/api/pedidos/7

###
// atualizar status
PATCH  http://localhost:3000/api/pedidos/9
Content-Type: application/json

{
    "status": "pendente"
}

###
//Atualizar pedido
PUT http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 2
        },
        {
            "produto_id": 2,
            "quantidade": 1
        },
        {
            "produto_id": 3,
            "quantidade": 4
        }
    ]
} 
